controller:
  image: "easy-jenkins"
  installPlugins: false
  jenkinsAdminEmail: admin@example.com
  jenkinsUrl: jenkins.example.com
  sidecars:
    configAutoReload:
      enabled: true
  tagLabel: "lts-jdk17"
  JCasC:
    authorizationStrategy: |-
      loggedInUsersCanDoAnything:
        allowAnonymousRead: false
    configScripts:
      welcome-message: |
        jenkins:
          systemMessage: Welcome to our CI/CD server.  Any changes made manually will be lost on daily pod restart.
    securityRealm: |-
      local:
        allowsSignup: false
        enableCaptcha: false
        users:
        - id: "${chart-admin-username}"
          name: "Jenkins Admin"
          password: "${chart-admin-password}"
