apiVersion: builtin
kind: LabelTransformer
metadata:
  name: global-labels
labels:
  app.kubernetes.io/name: jenkins
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/instance: %INSTANCE%
  pdpv2.panasonic.com/organization: panwell
  pdpv2.panasonic.com/department: sre
fieldSpecs:
- path: metadata/labels
  create: true
- path: spec/template/metadata/labels
  create: true
