---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins
  labels:
    "app.kubernetes.io/component": "jenkins-controller"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "8Gi"
