apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- config.yaml
- home-pvc.yaml
- jenkins-agent-svc.yaml
- jenkins-controller-statefulset.yaml
- jenkins-controller-svc.yaml
- rbac.yaml
- secret.yaml
- service-account.yaml
commonLabels:
  app.kubernetes.io/name: jenkins
  app.kubernetes.io/part-of: jenkins
transformers:
- global-labels.yaml
