apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- home-pvc.yaml
- jenkins-agent-svc.yaml
- jenkins-controller-statefulset.yaml
- jenkins-controller-svc.yaml
- rbac.yaml
- secret.yaml
- service-account.yaml
transformers:
- global-labels.yaml
