---
# Source: jenkins/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins
  namespace: default
  labels:
    "app.kubernetes.io/name": 'jenkins'
    "app.kubernetes.io/managed-by": ""
    "app.kubernetes.io/instance": "local"
    "app.kubernetes.io/component": "jenkins-controller"
